import ExcelJS from 'exceljs';
import { aggregateB2cs, aggregateSacSummary, invoicesByCategory, type GstrInvoiceRecord } from './gstr-aggregate.js';
import { stateNameFromCode } from './indian-states.js';

export type GstExportMeta = {
  companyName: string;
  gstin: string;
  filingPeriod: string;
  generatedAt: string;
  generatedBy: string;
};

function headerStyle() {
  return {
    font: { bold: true, color: { argb: 'FFFFFFFF' } },
    fill: { type: 'pattern' as const, pattern: 'solid' as const, fgColor: { argb: 'FF5C2E00' } },
  };
}

async function writeMetaRows(
  sheet: ExcelJS.Worksheet,
  meta: GstExportMeta,
  title: string,
) {
  sheet.addRow([title]);
  sheet.getRow(1).font = { bold: true, size: 14 };
  sheet.addRow(['Company', meta.companyName]);
  sheet.addRow(['GSTIN', meta.gstin]);
  sheet.addRow(['Filing Period', meta.filingPeriod]);
  sheet.addRow(['Generated', meta.generatedAt]);
  sheet.addRow(['Generated By', meta.generatedBy]);
  sheet.addRow([]);
}

function round2(n: number) {
  return Math.round(n * 100) / 100;
}

export async function buildGstr1Workbook(
  invoices: GstrInvoiceRecord[],
  meta: GstExportMeta,
): Promise<Buffer> {
  const wb = new ExcelJS.Workbook();
  const byCat = invoicesByCategory(invoices);
  const b2cs = aggregateB2cs(invoices);
  const sac = aggregateSacSummary(invoices);

  const summary = wb.addWorksheet('Summary');
  await writeMetaRows(summary, meta, 'GSTR-1 Export Summary');
  summary.addRow(['Category', 'Invoice Count', 'Taxable Value', 'Total GST', 'Gross Value']);
  const sumHeader = summary.lastRow!;
  Object.assign(sumHeader, { font: { bold: true } });
  for (const [cat, rows] of Object.entries(byCat)) {
    if (!rows.length) continue;
    const taxable = rows.reduce((s, r) => s + Number(r.subtotal ?? r.base_amount ?? 0), 0);
    const gst = rows.reduce((s, r) => s + Number(r.gst_total ?? 0), 0);
    const gross = rows.reduce((s, r) => s + Number(r.total_amount ?? 0), 0);
    summary.addRow([cat, rows.length, round2(taxable), round2(gst), round2(gross)]);
  }

  const b2b = wb.addWorksheet('B2B');
  await writeMetaRows(b2b, meta, 'B2B Invoices');
  b2b.addRow([
    'Invoice No', 'Date', 'Customer', 'GSTIN', 'State', 'SAC', 'Taxable', 'CGST', 'SGST', 'IGST', 'Total',
  ]);
  b2b.getRow(7).eachCell((c) => Object.assign(c, headerStyle()));
  for (const inv of byCat.B2B) {
    b2b.addRow([
      inv.invoice_number,
      inv.invoice_date,
      inv.customer_name,
      inv.customer_gstin || '',
      inv.place_of_supply || inv.customer_state || '',
      inv.sac_code || inv.hsn_sac_code || '',
      round2(Number(inv.subtotal ?? inv.base_amount ?? 0)),
      round2(Number(inv.cgst_amount || 0)),
      round2(Number(inv.sgst_amount || 0)),
      round2(Number(inv.igst_amount || 0)),
      round2(Number(inv.total_amount || 0)),
    ]);
  }

  const b2csSheet = wb.addWorksheet('B2CS');
  await writeMetaRows(b2csSheet, meta, 'B2CS — Aggregated by State & Rate');
  b2csSheet.addRow(['State', 'Code', 'GST %', 'Invoices', 'Taxable', 'CGST', 'SGST', 'IGST', 'Total GST', 'Gross']);
  b2csSheet.getRow(7).eachCell((c) => Object.assign(c, headerStyle()));
  for (const row of b2cs) {
    b2csSheet.addRow([
      row.stateName,
      row.stateCode,
      row.gstRate,
      row.invoiceCount,
      round2(row.taxableValue),
      round2(row.cgst),
      round2(row.sgst),
      round2(row.igst),
      round2(row.totalGst),
      round2(row.grossValue),
    ]);
  }

  const b2cl = wb.addWorksheet('B2CL');
  await writeMetaRows(b2cl, meta, 'B2CL — Large Inter-State Unregistered');
  b2cl.addRow(['Invoice No', 'Date', 'Customer', 'State', 'Taxable', 'IGST', 'Total']);
  b2cl.getRow(7).eachCell((c) => Object.assign(c, headerStyle()));
  for (const inv of byCat.B2CL) {
    b2cl.addRow([
      inv.invoice_number,
      inv.invoice_date,
      inv.customer_name,
      inv.place_of_supply || stateNameFromCode(inv.customer_state_code || '') || '',
      round2(Number(inv.subtotal ?? inv.base_amount ?? 0)),
      round2(Number(inv.igst_amount || 0)),
      round2(Number(inv.total_amount || 0)),
    ]);
  }

  const cdnr = wb.addWorksheet('CDNR');
  await writeMetaRows(cdnr, meta, 'CDNR — Credit Notes (GST Registered)');
  cdnr.addRow(['Invoice No', 'Date', 'Customer', 'GSTIN', 'State', 'SAC', 'Taxable', 'CGST', 'SGST', 'IGST', 'Total']);
  cdnr.getRow(7).eachCell((c) => Object.assign(c, headerStyle()));
  for (const inv of byCat.CDNR) {
    cdnr.addRow([
      inv.invoice_number,
      inv.invoice_date,
      inv.customer_name,
      inv.customer_gstin || '',
      inv.place_of_supply || inv.customer_state || '',
      inv.sac_code || inv.hsn_sac_code || '',
      round2(Number(inv.subtotal ?? inv.base_amount ?? 0)),
      round2(Number(inv.cgst_amount || 0)),
      round2(Number(inv.sgst_amount || 0)),
      round2(Number(inv.igst_amount || 0)),
      round2(Number(inv.total_amount || 0)),
    ]);
  }

  const cdnur = wb.addWorksheet('CDNUR');
  await writeMetaRows(cdnur, meta, 'CDNUR — Credit Notes (Unregistered)');
  cdnur.addRow(['Invoice No', 'Date', 'Customer', 'State', 'Taxable', 'IGST', 'Total']);
  cdnur.getRow(7).eachCell((c) => Object.assign(c, headerStyle()));
  for (const inv of byCat.CDNUR) {
    cdnur.addRow([
      inv.invoice_number,
      inv.invoice_date,
      inv.customer_name,
      inv.place_of_supply || stateNameFromCode(inv.customer_state_code || '') || '',
      round2(Number(inv.subtotal ?? inv.base_amount ?? 0)),
      round2(Number(inv.igst_amount || 0)),
      round2(Number(inv.total_amount || 0)),
    ]);
  }

  const sacSheet = wb.addWorksheet('SAC Summary');
  await writeMetaRows(sacSheet, meta, 'SAC / HSN Summary');
  sacSheet.addRow(['SAC', 'GST %', 'Invoices', 'Qty', 'Taxable', 'CGST', 'SGST', 'IGST', 'Total GST', 'Gross']);
  sacSheet.getRow(7).eachCell((c) => Object.assign(c, headerStyle()));
  for (const row of sac) {
    sacSheet.addRow([
      row.sacCode,
      row.gstRate,
      row.invoiceCount,
      row.quantity,
      round2(row.taxableValue),
      round2(row.cgst),
      round2(row.sgst),
      round2(row.igst),
      round2(row.totalGst),
      round2(row.grossValue),
    ]);
  }

  const buffer = await wb.xlsx.writeBuffer();
  return Buffer.from(buffer);
}

export async function buildGstSummaryWorkbook(
  invoices: GstrInvoiceRecord[],
  meta: GstExportMeta,
): Promise<Buffer> {
  const wb = new ExcelJS.Workbook();
  const sheet = wb.addWorksheet('GST Summary');
  await writeMetaRows(sheet, meta, 'GST Summary Report');

  const taxable = invoices.reduce((s, r) => s + Number(r.subtotal ?? r.base_amount ?? 0), 0);
  const cgst = invoices.reduce((s, r) => s + Number(r.cgst_amount || 0), 0);
  const sgst = invoices.reduce((s, r) => s + Number(r.sgst_amount || 0), 0);
  const igst = invoices.reduce((s, r) => s + Number(r.igst_amount || 0), 0);
  const gross = invoices.reduce((s, r) => s + Number(r.total_amount || 0), 0);

  sheet.addRow(['Total Invoices', invoices.length]);
  sheet.addRow(['Taxable Value', round2(taxable)]);
  sheet.addRow(['CGST', round2(cgst)]);
  sheet.addRow(['SGST', round2(sgst)]);
  sheet.addRow(['IGST', round2(igst)]);
  sheet.addRow(['Gross Invoice Value', round2(gross)]);

  const buffer = await wb.xlsx.writeBuffer();
  return Buffer.from(buffer);
}

export async function buildSalesRegisterWorkbook(
  invoices: GstrInvoiceRecord[],
  meta: GstExportMeta,
): Promise<Buffer> {
  const wb = new ExcelJS.Workbook();
  const sheet = wb.addWorksheet('Sales Register');
  await writeMetaRows(sheet, meta, 'Monthly Sales Register');
  sheet.addRow([
    'Invoice No', 'Date', 'Customer', 'GSTIN', 'Category', 'State', 'SAC', 'Service',
    'Taxable', 'CGST', 'SGST', 'IGST', 'Total',
  ]);
  sheet.getRow(7).eachCell((c) => Object.assign(c, headerStyle()));
  for (const inv of invoices) {
    sheet.addRow([
      inv.invoice_number,
      inv.invoice_date,
      inv.customer_name,
      inv.customer_gstin || '',
      inv.gstr_category || 'B2CS',
      inv.place_of_supply || inv.customer_state || '',
      inv.sac_code || inv.hsn_sac_code || '',
      inv.service_title,
      round2(Number(inv.subtotal ?? inv.base_amount ?? 0)),
      round2(Number(inv.cgst_amount || 0)),
      round2(Number(inv.sgst_amount || 0)),
      round2(Number(inv.igst_amount || 0)),
      round2(Number(inv.total_amount || 0)),
    ]);
  }
  const buffer = await wb.xlsx.writeBuffer();
  return Buffer.from(buffer);
}

export async function buildSacSummaryWorkbook(
  invoices: GstrInvoiceRecord[],
  meta: GstExportMeta,
): Promise<Buffer> {
  const wb = new ExcelJS.Workbook();
  const sheet = wb.addWorksheet('SAC Summary');
  const rows = aggregateSacSummary(invoices);
  await writeMetaRows(sheet, meta, 'SAC Summary Report');
  sheet.addRow(['SAC', 'GST %', 'Invoices', 'Qty', 'Taxable', 'CGST', 'SGST', 'IGST', 'Total GST', 'Gross']);
  sheet.getRow(7).eachCell((c) => Object.assign(c, headerStyle()));
  for (const row of rows) {
    sheet.addRow([
      row.sacCode,
      row.gstRate,
      row.invoiceCount,
      row.quantity,
      round2(row.taxableValue),
      round2(row.cgst),
      round2(row.sgst),
      round2(row.igst),
      round2(row.totalGst),
      round2(row.grossValue),
    ]);
  }
  const buffer = await wb.xlsx.writeBuffer();
  return Buffer.from(buffer);
}
